.TH ebs-backup 1 2022-04-22 1.0.0-alpha.1

.SH NAME
ebs-backup \- backup up files onto an AWS EBS volume

.SH SYNOPSIS

.B ebs-backup
.I keyname
.I zone
.IR file ...

.SH DESCRIPTION
.B ebs-backup
uses the AWS key pair
.I keyname
to backup each
.I file
to an EBS volume in the availability zone named
.IR zone .


If the user has not created an AWS key pair, then the user must
create an AWS key pair (see
.UR https://\:docs.aws.amazon.com/\:AWSEC2/\:latest/\:UserGuide/\:ec2-key-pairs.html
.UE ).

Backup volumes are EBS volumes tagged with the Key "ebs-backup-vol" and Value
"1". If no EBS volumes have this key,value pair, then the user will be prompted
to create such a volume.
.B ebs-backup
will not perform backup or restoration unless a backup volume exists.

The provided
.I zone
must be the same as existing backup volumes, otherwise,
.B ebs-backup
cannot use the existing backup volumes and will run as if those volumes do not
exist.

Backups are located in a btrfs filesystem under "backup.n/". The smaller n is,
the more recent the backup (with n=0 indicating that the backup is the latest
backup).

.SS Restoration
The paths of files relative to root (/) on the local system (where
.B ebs-backup
runs) are the same as the backed up files' paths relative to their respective
backup directory. Therefore, to restore the nth backup (starting at n=0), run:

.RS 4
$
.B scp user@remote:mnt/backup.n
.RE 

where user is the user on an AWS EC2 instance on which the backup volume is
attached, remote is the public dns name of the EC2 instance in-use, and mnt is
the mount point of the backup volume.
